# Generated by Django 4.2.16 on 2024-11-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_fname', models.CharField(max_length=50)),
                ('r_lname', models.CharField(max_length=50)),
                ('r_department', models.CharField(choices=[('', 'Select'), ('MIS', 'MIS'), ('OPERATIONS', 'OPERATIONS'), ('FINANCE', 'FINANCE'), ('HR', 'HR'), ('MERCH', 'MERCH'), ('SALES', 'SALES'), ('MARKETING', 'MARKETING')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('arrival_date', models.DateTimeField()),
                ('relationship', models.CharField(choices=[('', 'Select'), ('Grandparent', 'Grandparent'), ('Parent', 'Parent'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Sibling', 'Sibling'), ('Cousin', 'Cousin'), ('Spouse', 'Spouse'), ('Partner', 'Partner')], max_length=50)),
                ('voucher_id', models.CharField(blank=True, max_length=9, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='app.relative')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='app.userentry')),
            ],
            options={
                'ordering': ['status', '-created'],
            },
        ),
    ]
