# Generated by Django 4.2.16 on 2024-11-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='relative',
            unique_together={('r_fname', 'r_lname')},
        ),
    ]
