# Generated by Django 4.2.16 on 2024-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_qrcode_status_alter_relative_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='status_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
